version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend-oficina
    environment:
      - POSTGRES_DB=oficina_4nmy
      - POSTGRES_USER=oficina_4nmy_user
      - POSTGRES_PASSWORD=8gZrhb7WlpdgtlhFmld5mskcI4V0Q0LY
      - POSTGRES_HOST=dpg-cujcnol6l47c73d2bbl0-a.oregon-postgres.render.com
      - PORT=3000
      - JWT_SECRET=secret
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    container_name: frontend-oficina
    ports:
      - "3001:3000"
    depends_on:
      - backend